from __future__ import annotations


LANGUAGES: tuple[tuple[str, str], ...] = (
    ("en", "English"),
    ("ar", "العربية"),
    ("es", "Español"),
    ("fr", "Français"),
    ("ja", "日本語"),
    ("ko", "한국어"),
    ("vi", "Tiếng Việt"),
    ("zh-Hans", "简体中文"),
    ("zh-Hant", "繁體中文"),
    ("de", "Deutsch"),
    ("ru", "Русский"),
)


_ENGLISH = {
    "language_tooltip": "Choose language",
    "guide_downloads": "Guide & downloads",
    "hero_eyebrow": "BOOKS, NOT SETUP",
    "hero_title": "Send a book in under a minute.",
    "hero_description": "No terminal commands. Pair over Wi-Fi with KOReader's no-password option, or use USB when Kindle storage is available.",
    "preparing_key": "Preparing your private Kindle key...",
    "on_kindle": "On your Kindle",
    "step_network": "Use the same or another routed local network",
    "step_open": "Open KOReader",
    "step_ssh": "First use: allow no password, then start SSH",
    "your_kindle": "Your Kindle",
    "device_hint": "Enter any reachable Kindle address, or leave it blank to scan every active private interface.",
    "address_placeholder": "IP, hostname, host:port, or [IPv6]:port",
    "pair_usb": "Pair over USB",
    "connect_find": "Connect / find Kindle",
    "no_password_label": "First connection: KOReader allows login without password",
    "no_password_tooltip": "The app will use no-password access once, install this computer's public key, and verify key login. It will not disable the Kindle setting.",
    "firewall_help": "Windows firewall help",
    "books_to_send": "Books to send",
    "book_count": "{count} book(s) · {size}",
    "col_book": "Book",
    "col_format": "Format",
    "col_size": "Size",
    "choose_books": "Choose books",
    "remove_selected": "Remove selected",
    "destination": "Destination: {path}",
    "ready_pairing": "Ready for pairing and discovery.",
    "cancel": "Cancel",
    "send_books": "Send books",
    "footer": "Version {version}  ·  Private key stays on this computer  ·  Stop KOReader SSH when finished",
    "drop_books": "Drop books here",
    "drop_subtitle": "or click to choose PDF, EPUB, MOBI and other KOReader files",
    "usb_attention": "USB pairing needs attention: {error}",
    "usb_ready": "USB pairing is ready. Safely eject, open KOReader, and start its SSH server.",
    "paired_auto": "Paired automatically on {roots}. The private key stays on this computer.",
    "usb_complete_eject": "USB pairing complete. Safely eject before using Wi-Fi.",
    "ready_previous": "Ready to look for the previously used Kindle at {address}.",
    "first_use_usb": "First use: connect the Kindle by USB once for automatic pairing, or use no-password Wi-Fi pairing.",
    "usb_pair_failed": "USB pairing failed",
    "connect_usb_title": "Connect the Kindle by USB",
    "usb_not_found": "No mounted KOReader Kindle storage was found.\n\nIf KOReader is open, exit KOReader first. Then connect a USB data cable, wait for the Kindle drive to appear, and click Pair over USB again.\n\nTo keep KOReader open, use Wi-Fi pairing with the no-password checkbox instead.",
    "paired_status": "Paired. Safely eject, open KOReader, and start Tools → SSH server.",
    "key_installed": "Public key installed on {roots}. No password is needed.",
    "usb_complete": "USB pairing complete.",
    "kindle_paired": "Kindle paired",
    "pairing_complete": "Pairing is complete.\n\nSafely eject and unplug the Kindle, connect it to the same Wi-Fi, open KOReader, and start Tools > SSH server.",
    "firewall_dialog_title": "Windows firewall help",
    "firewall_dialog": "Kindle Book Sender is an outbound SSH client. Windows normally permits this without a rule.\n\nCreate an explicit outbound allow rule for TCP port {port}? Windows will show a UAC administrator prompt.\n\nThis cannot fix guest-Wi-Fi/client isolation, a wrong address, VPN routing, or a stopped Kindle SSH server.",
    "firewall_requested": "Windows requested an outbound TCP {port} firewall rule. Approve the UAC prompt, then connect again.",
    "firewall_failed": "Windows could not start the elevated firewall helper.",
    "looking": "Looking for your Kindle on the local network...",
    "searching": "Searching for KOReader SSH on the same Wi-Fi...",
    "connected": "Kindle connected - {address}",
    "bootstrap_success": "Passwordless bootstrap succeeded. This computer's public key was installed and key login was verified.",
    "key_verified": "Verified with this computer's private pairing key and the KOReader installation.",
    "kindle_found": "Kindle found. Add books, then click Send books.",
    "choose_dialog": "Choose books to send to KOReader",
    "connecting": "Connecting to {address}...",
    "transfer_complete": "Transfer complete · {count} book(s) sent",
    "sent_size": "Sent {size}. Refresh KOReader's file browser.",
    "books_sent": "Books sent",
    "books_sent_message": "{count} book(s) sent successfully.\n\nFind them in documents/Books in KOReader.",
    "action_needed": "Action needed",
    "cancelling": "Cancelling...",
    "supplied_invalid": "The supplied Kindle address is invalid: {error}",
    "testing_supplied": "Testing the supplied address {address} first...",
    "no_private_network": "No private Wi-Fi or Ethernet network was found on this computer.",
    "searching_networks": "Searching {count} active private network(s) for KOReader SSH...",
    "checking_possible": "Checking a possible Kindle at {address}...",
    "supplied_tested": "The supplied address {address} was tested first: {error}",
    "endpoints_unverified": "Found {count} local SSH endpoint(s), but none verified as this KOReader Kindle.",
    "no_tcp_answer": "No local device answered on TCP 2222. Confirm KOReader SSH is started and the Wi-Fi does not isolate clients.",
    "new_computer_help": "For a new computer, stop KOReader SSH, enable 'Login without password (DANGEROUS)', start SSH, check the app's no-password option, and connect again.",
    "sending_file": "Sending {name} - {sent} of {size}",
    "no_readable_files": "No readable book files were selected.",
    "connecting_secure": "Connecting securely to {address}...",
    "create_books_failed": "Could not create the Books folder.",
    "transfer_cancelled": "Transfer cancelled.",
    "connection_closed": "The Kindle connection closed unexpectedly.",
    "sent_book_count": "Sent {count} book(s).",
    "book_filter": "KOReader books (*.pdf *.epub *.mobi *.azw *.azw3 *.djvu *.cbz *.cbr *.cbt *.docx *.rtf *.txt *.html *.htm *.fb2 *.xps *.md);;PDF books (*.pdf);;EPUB books (*.epub);;All files (*)",
}


_TRANSLATIONS = {
    "en": _ENGLISH,
    "ar": {
        "language_tooltip": "اختر اللغة", "guide_downloads": "الدليل والتنزيلات", "hero_eyebrow": "الكتب، بلا إعداد معقد", "hero_title": "أرسل كتابًا خلال أقل من دقيقة.",
        "hero_description": "لا أوامر طرفية. اقترن عبر Wi-Fi بخيار KOReader للدخول بلا كلمة مرور، أو استخدم USB عندما تكون مساحة Kindle متاحة.", "preparing_key": "جارٍ تجهيز مفتاح Kindle الخاص...", "on_kindle": "على جهاز Kindle", "step_network": "استخدم الشبكة المحلية نفسها أو شبكة محلية موجّهة", "step_open": "افتح KOReader", "step_ssh": "في أول استخدام: اسمح بالدخول بلا كلمة مرور ثم شغّل SSH",
        "your_kindle": "جهاز Kindle", "device_hint": "أدخل أي عنوان Kindle يمكن الوصول إليه، أو اتركه فارغًا لفحص كل واجهات الشبكة الخاصة النشطة.", "address_placeholder": "IP أو اسم مضيف أو host:port أو [IPv6]:port", "pair_usb": "اقتران عبر USB", "connect_find": "اتصال / بحث عن Kindle", "no_password_label": "الاتصال الأول: يسمح KOReader بالدخول بلا كلمة مرور", "no_password_tooltip": "سيستخدم التطبيق الدخول بلا كلمة مرور مرة واحدة، ويثبّت المفتاح العام لهذا الكمبيوتر، ثم يتحقق من دخول المفتاح. لن يغيّر إعداد Kindle.", "firewall_help": "مساعدة جدار حماية Windows",
        "books_to_send": "الكتب المراد إرسالها", "book_count": "{count} كتاب · {size}", "col_book": "الكتاب", "col_format": "التنسيق", "col_size": "الحجم", "choose_books": "اختر الكتب", "remove_selected": "إزالة المحدد", "destination": "الوجهة: {path}", "ready_pairing": "جاهز للاقتران والبحث.", "cancel": "إلغاء", "send_books": "إرسال الكتب", "footer": "الإصدار {version}  ·  يبقى المفتاح الخاص على هذا الكمبيوتر  ·  أوقف SSH في KOReader عند الانتهاء", "drop_books": "أفلت الكتب هنا", "drop_subtitle": "أو انقر لاختيار PDF وEPUB وMOBI وملفات KOReader الأخرى",
        "usb_attention": "يتطلب اقتران USB الانتباه: {error}", "usb_ready": "اقتران USB جاهز. أخرج الجهاز بأمان، وافتح KOReader، ثم شغّل خادم SSH.", "paired_auto": "تم الاقتران تلقائيًا على {roots}. يبقى المفتاح الخاص على هذا الكمبيوتر.", "usb_complete_eject": "اكتمل اقتران USB. أخرج الجهاز بأمان قبل استخدام Wi-Fi.", "ready_previous": "جاهز للبحث عن جهاز Kindle السابق عند {address}.", "first_use_usb": "لأول استخدام: صِل Kindle مرة واحدة عبر USB للاقتران التلقائي، أو استخدم اقتران Wi-Fi بلا كلمة مرور.", "usb_pair_failed": "فشل اقتران USB", "connect_usb_title": "صِل Kindle عبر USB", "usb_not_found": "لم يتم العثور على مساحة Kindle مركبة تحتوي KOReader.\n\nإذا كان KOReader مفتوحًا، فاخرج منه أولًا. صِل كابل بيانات USB، وانتظر ظهور محرك Kindle، ثم انقر اقتران عبر USB مجددًا.\n\nلإبقاء KOReader مفتوحًا، استخدم اقتران Wi-Fi مع خيار بلا كلمة مرور.", "paired_status": "تم الاقتران. أخرج الجهاز بأمان، وافتح KOReader، ثم شغّل أدوات ← خادم SSH.", "key_installed": "تم تثبيت المفتاح العام على {roots}. لا حاجة إلى كلمة مرور.", "usb_complete": "اكتمل اقتران USB.", "kindle_paired": "تم اقتران Kindle", "pairing_complete": "اكتمل الاقتران.\n\nأخرج Kindle وافصله بأمان، وصِله بالشبكة نفسها، وافتح KOReader، ثم شغّل أدوات > خادم SSH.",
        "firewall_dialog_title": "مساعدة جدار حماية Windows", "firewall_dialog": "Kindle Book Sender عميل SSH صادر، ويسمح Windows به عادةً دون قاعدة.\n\nهل تريد إنشاء قاعدة سماح صريحة لمنفذ TCP {port}؟ سيعرض Windows طلب مسؤول UAC.\n\nلا يصلح هذا عزل أجهزة Wi-Fi أو عنوانًا خاطئًا أو توجيه VPN أو توقف خادم SSH على Kindle.", "firewall_requested": "طلب Windows قاعدة صادرة لمنفذ TCP {port}. وافق على طلب UAC ثم أعد الاتصال.", "firewall_failed": "تعذر على Windows تشغيل مساعد جدار الحماية بصلاحيات مرتفعة.",
        "looking": "جارٍ البحث عن Kindle على الشبكة المحلية...", "searching": "جارٍ البحث عن SSH الخاص بـ KOReader على شبكة Wi-Fi...", "connected": "تم اتصال Kindle - {address}", "bootstrap_success": "نجح الإعداد بلا كلمة مرور. ثُبّت المفتاح العام لهذا الكمبيوتر وتم التحقق من دخوله.", "key_verified": "تم التحقق بمفتاح الاقتران الخاص لهذا الكمبيوتر وبتثبيت KOReader.", "kindle_found": "تم العثور على Kindle. أضف الكتب ثم انقر إرسال الكتب.", "choose_dialog": "اختر كتبًا لإرسالها إلى KOReader", "connecting": "جارٍ الاتصال بـ {address}...", "transfer_complete": "اكتمل النقل · تم إرسال {count} كتاب", "sent_size": "تم إرسال {size}. حدّث متصفح ملفات KOReader.", "books_sent": "تم إرسال الكتب", "books_sent_message": "تم إرسال {count} كتاب بنجاح.\n\nستجدها في documents/Books داخل KOReader.", "action_needed": "يلزم إجراء", "cancelling": "جارٍ الإلغاء...",
        "supplied_invalid": "عنوان Kindle المُدخل غير صالح: {error}", "testing_supplied": "جارٍ اختبار العنوان المُدخل {address} أولًا...", "no_private_network": "لم يتم العثور على شبكة Wi-Fi أو Ethernet خاصة على هذا الكمبيوتر.", "searching_networks": "جارٍ فحص {count} شبكة خاصة نشطة بحثًا عن SSH الخاص بـ KOReader...", "checking_possible": "جارٍ فحص Kindle محتمل عند {address}...", "supplied_tested": "تم اختبار العنوان {address} أولًا: {error}", "endpoints_unverified": "تم العثور على {count} نقطة SSH محلية، لكن لم يتم التحقق من أنها Kindle مع KOReader.", "no_tcp_answer": "لم يستجب جهاز محلي على TCP 2222. تأكد من تشغيل SSH في KOReader ومن أن Wi-Fi لا يعزل الأجهزة.", "new_computer_help": "على كمبيوتر جديد، أوقف SSH في KOReader، وفعّل الدخول بلا كلمة مرور، ثم شغّل SSH وحدد خيار بلا كلمة مرور في التطبيق وأعد الاتصال.", "sending_file": "إرسال {name} - {sent} من {size}", "no_readable_files": "لم يتم تحديد ملفات كتب قابلة للقراءة.", "connecting_secure": "اتصال آمن بـ {address}...", "create_books_failed": "تعذر إنشاء مجلد Books.", "transfer_cancelled": "تم إلغاء النقل.", "connection_closed": "أُغلق اتصال Kindle بشكل غير متوقع.", "sent_book_count": "تم إرسال {count} كتاب.",
    },
    "es": {
        "language_tooltip": "Elegir idioma", "guide_downloads": "Guía y descargas", "hero_eyebrow": "LIBROS, SIN CONFIGURACIÓN", "hero_title": "Envía un libro en menos de un minuto.", "hero_description": "Sin comandos de terminal. Empareja por Wi-Fi con la opción sin contraseña de KOReader, o usa USB cuando el almacenamiento del Kindle esté disponible.", "preparing_key": "Preparando tu clave privada de Kindle...", "on_kindle": "En tu Kindle", "step_network": "Usa la misma red local u otra con ruta", "step_open": "Abre KOReader", "step_ssh": "Primer uso: permite acceso sin contraseña e inicia SSH", "your_kindle": "Tu Kindle", "device_hint": "Introduce cualquier dirección Kindle accesible o déjala vacía para explorar todas las interfaces privadas activas.", "address_placeholder": "IP, nombre, host:puerto o [IPv6]:puerto", "pair_usb": "Emparejar por USB", "connect_find": "Conectar / buscar Kindle", "no_password_label": "Primera conexión: KOReader permite entrar sin contraseña", "no_password_tooltip": "La aplicación usará el acceso sin contraseña una vez, instalará la clave pública de este equipo y verificará el acceso por clave. No cambiará el ajuste del Kindle.", "firewall_help": "Ayuda del firewall de Windows",
        "books_to_send": "Libros para enviar", "book_count": "{count} libros · {size}", "col_book": "Libro", "col_format": "Formato", "col_size": "Tamaño", "choose_books": "Elegir libros", "remove_selected": "Quitar selección", "destination": "Destino: {path}", "ready_pairing": "Listo para emparejar y buscar.", "cancel": "Cancelar", "send_books": "Enviar libros", "footer": "Versión {version}  ·  La clave privada permanece en este equipo  ·  Detén SSH de KOReader al terminar", "drop_books": "Suelta los libros aquí", "drop_subtitle": "o haz clic para elegir PDF, EPUB, MOBI y otros archivos de KOReader",
        "usb_attention": "El emparejamiento USB requiere atención: {error}", "usb_ready": "El emparejamiento USB está listo. Expulsa con seguridad, abre KOReader e inicia su servidor SSH.", "paired_auto": "Emparejado automáticamente en {roots}. La clave privada permanece en este equipo.", "usb_complete_eject": "Emparejamiento USB completo. Expulsa antes de usar Wi-Fi.", "ready_previous": "Listo para buscar el Kindle usado anteriormente en {address}.", "first_use_usb": "Primer uso: conecta una vez el Kindle por USB para emparejar automáticamente, o usa Wi-Fi sin contraseña.", "usb_pair_failed": "Falló el emparejamiento USB", "connect_usb_title": "Conecta el Kindle por USB", "usb_not_found": "No se encontró un almacenamiento Kindle montado con KOReader.\n\nSi KOReader está abierto, sal primero. Conecta un cable USB de datos, espera a que aparezca la unidad Kindle y vuelve a pulsar Emparejar por USB.\n\nPara mantener KOReader abierto, usa el emparejamiento Wi-Fi sin contraseña.", "paired_status": "Emparejado. Expulsa con seguridad, abre KOReader e inicia Herramientas → Servidor SSH.", "key_installed": "Clave pública instalada en {roots}. No se necesita contraseña.", "usb_complete": "Emparejamiento USB completo.", "kindle_paired": "Kindle emparejado", "pairing_complete": "El emparejamiento está completo.\n\nExpulsa y desconecta el Kindle, conéctalo al mismo Wi-Fi, abre KOReader e inicia Herramientas > Servidor SSH.",
        "firewall_dialog_title": "Ayuda del firewall de Windows", "firewall_dialog": "Kindle Book Sender es un cliente SSH saliente. Windows suele permitirlo sin una regla.\n\n¿Crear una regla de salida explícita para el puerto TCP {port}? Windows mostrará una solicitud UAC de administrador.\n\nEsto no corrige el aislamiento Wi-Fi, una dirección errónea, rutas VPN ni un servidor SSH detenido.", "firewall_requested": "Windows solicitó una regla de salida TCP {port}. Aprueba UAC y vuelve a conectar.", "firewall_failed": "Windows no pudo iniciar el asistente elevado del firewall.", "looking": "Buscando tu Kindle en la red local...", "searching": "Buscando SSH de KOReader en la misma Wi-Fi...", "connected": "Kindle conectado - {address}", "bootstrap_success": "La configuración sin contraseña funcionó. Se instaló la clave pública de este equipo y se verificó el acceso por clave.", "key_verified": "Verificado con la clave privada de emparejamiento de este equipo y la instalación de KOReader.", "kindle_found": "Kindle encontrado. Añade libros y pulsa Enviar libros.", "choose_dialog": "Elige libros para enviar a KOReader", "connecting": "Conectando con {address}...", "transfer_complete": "Transferencia completa · {count} libros enviados", "sent_size": "Enviados {size}. Actualiza el explorador de archivos de KOReader.", "books_sent": "Libros enviados", "books_sent_message": "Se enviaron correctamente {count} libros.\n\nEstán en documents/Books dentro de KOReader.", "action_needed": "Acción necesaria", "cancelling": "Cancelando...",
        "supplied_invalid": "La dirección Kindle indicada no es válida: {error}", "testing_supplied": "Probando primero la dirección {address}...", "no_private_network": "No se encontró una red Wi-Fi o Ethernet privada en este equipo.", "searching_networks": "Buscando SSH de KOReader en {count} redes privadas activas...", "checking_possible": "Comprobando un posible Kindle en {address}...", "supplied_tested": "La dirección {address} se probó primero: {error}", "endpoints_unverified": "Se encontraron {count} servicios SSH locales, pero ninguno se verificó como este Kindle con KOReader.", "no_tcp_answer": "Ningún dispositivo local respondió en TCP 2222. Confirma que SSH de KOReader esté iniciado y que la Wi-Fi no aísle clientes.", "new_computer_help": "En un equipo nuevo, detén SSH de KOReader, activa el acceso sin contraseña, reinicia SSH, marca la opción sin contraseña en la app y vuelve a conectar.", "sending_file": "Enviando {name} - {sent} de {size}", "no_readable_files": "No se seleccionaron archivos de libro legibles.", "connecting_secure": "Conectando de forma segura con {address}...", "create_books_failed": "No se pudo crear la carpeta Books.", "transfer_cancelled": "Transferencia cancelada.", "connection_closed": "La conexión con el Kindle se cerró inesperadamente.", "sent_book_count": "Enviados {count} libros.",
    },
    "fr": {
        "language_tooltip": "Choisir la langue", "guide_downloads": "Guide et téléchargements", "hero_eyebrow": "DES LIVRES, PAS DE CONFIGURATION", "hero_title": "Envoyez un livre en moins d’une minute.", "hero_description": "Aucune commande de terminal. Associez en Wi-Fi avec l’option sans mot de passe de KOReader, ou utilisez l’USB lorsque le stockage Kindle est disponible.", "preparing_key": "Préparation de votre clé Kindle privée...", "on_kindle": "Sur votre Kindle", "step_network": "Utilisez le même réseau local ou un autre réseau routé", "step_open": "Ouvrez KOReader", "step_ssh": "Première utilisation : autorisez l’accès sans mot de passe, puis démarrez SSH", "your_kindle": "Votre Kindle", "device_hint": "Saisissez une adresse Kindle joignable, ou laissez vide pour analyser toutes les interfaces privées actives.", "address_placeholder": "IP, nom d’hôte, hôte:port ou [IPv6]:port", "pair_usb": "Associer par USB", "connect_find": "Connecter / trouver le Kindle", "no_password_label": "Première connexion : KOReader autorise l’accès sans mot de passe", "no_password_tooltip": "L’application utilisera une fois l’accès sans mot de passe, installera la clé publique de cet ordinateur et vérifiera la connexion par clé. Elle ne modifiera pas le réglage du Kindle.", "firewall_help": "Aide du pare-feu Windows",
        "books_to_send": "Livres à envoyer", "book_count": "{count} livres · {size}", "col_book": "Livre", "col_format": "Format", "col_size": "Taille", "choose_books": "Choisir des livres", "remove_selected": "Retirer la sélection", "destination": "Destination : {path}", "ready_pairing": "Prêt pour l’association et la détection.", "cancel": "Annuler", "send_books": "Envoyer les livres", "footer": "Version {version}  ·  La clé privée reste sur cet ordinateur  ·  Arrêtez SSH de KOReader une fois terminé", "drop_books": "Déposez les livres ici", "drop_subtitle": "ou cliquez pour choisir des PDF, EPUB, MOBI et autres fichiers KOReader",
        "usb_attention": "L’association USB demande votre attention : {error}", "usb_ready": "L’association USB est prête. Éjectez en toute sécurité, ouvrez KOReader et démarrez son serveur SSH.", "paired_auto": "Association automatique effectuée sur {roots}. La clé privée reste sur cet ordinateur.", "usb_complete_eject": "Association USB terminée. Éjectez avant d’utiliser le Wi-Fi.", "ready_previous": "Prêt à rechercher le Kindle utilisé précédemment à l’adresse {address}.", "first_use_usb": "Première utilisation : connectez une fois le Kindle en USB pour l’association automatique, ou utilisez le Wi-Fi sans mot de passe.", "usb_pair_failed": "Échec de l’association USB", "connect_usb_title": "Connectez le Kindle en USB", "usb_not_found": "Aucun stockage Kindle monté avec KOReader n’a été trouvé.\n\nSi KOReader est ouvert, quittez-le d’abord. Branchez un câble USB de données, attendez l’apparition du lecteur Kindle, puis cliquez de nouveau sur Associer par USB.\n\nPour garder KOReader ouvert, utilisez l’association Wi-Fi sans mot de passe.", "paired_status": "Associé. Éjectez en toute sécurité, ouvrez KOReader, puis démarrez Outils → Serveur SSH.", "key_installed": "Clé publique installée sur {roots}. Aucun mot de passe n’est nécessaire.", "usb_complete": "Association USB terminée.", "kindle_paired": "Kindle associé", "pairing_complete": "L’association est terminée.\n\nÉjectez et débranchez le Kindle, connectez-le au même Wi-Fi, ouvrez KOReader, puis démarrez Outils > Serveur SSH.",
        "firewall_dialog_title": "Aide du pare-feu Windows", "firewall_dialog": "Kindle Book Sender est un client SSH sortant. Windows l’autorise normalement sans règle.\n\nCréer une règle sortante explicite pour le port TCP {port} ? Windows affichera une demande administrateur UAC.\n\nCela ne corrige pas l’isolation Wi-Fi, une mauvaise adresse, le routage VPN ou un serveur SSH Kindle arrêté.", "firewall_requested": "Windows a demandé une règle sortante TCP {port}. Approuvez l’UAC, puis reconnectez-vous.", "firewall_failed": "Windows n’a pas pu démarrer l’assistant de pare-feu avec élévation.", "looking": "Recherche de votre Kindle sur le réseau local...", "searching": "Recherche du SSH KOReader sur le même Wi-Fi...", "connected": "Kindle connecté - {address}", "bootstrap_success": "L’amorçage sans mot de passe a réussi. La clé publique de cet ordinateur a été installée et la connexion par clé vérifiée.", "key_verified": "Vérifié avec la clé privée d’association de cet ordinateur et l’installation de KOReader.", "kindle_found": "Kindle trouvé. Ajoutez des livres, puis cliquez sur Envoyer les livres.", "choose_dialog": "Choisissez les livres à envoyer à KOReader", "connecting": "Connexion à {address}...", "transfer_complete": "Transfert terminé · {count} livres envoyés", "sent_size": "{size} envoyés. Actualisez le navigateur de fichiers de KOReader.", "books_sent": "Livres envoyés", "books_sent_message": "{count} livres ont été envoyés.\n\nRetrouvez-les dans documents/Books dans KOReader.", "action_needed": "Action requise", "cancelling": "Annulation...",
        "supplied_invalid": "L’adresse Kindle fournie est invalide : {error}", "testing_supplied": "Test prioritaire de l’adresse {address}...", "no_private_network": "Aucun réseau Wi-Fi ou Ethernet privé n’a été trouvé sur cet ordinateur.", "searching_networks": "Recherche du SSH KOReader sur {count} réseaux privés actifs...", "checking_possible": "Vérification d’un Kindle possible à {address}...", "supplied_tested": "L’adresse {address} a été testée en premier : {error}", "endpoints_unverified": "{count} services SSH locaux trouvés, mais aucun n’a été vérifié comme ce Kindle KOReader.", "no_tcp_answer": "Aucun appareil local n’a répondu sur TCP 2222. Vérifiez que SSH de KOReader est démarré et que le Wi-Fi n’isole pas les clients.", "new_computer_help": "Sur un nouvel ordinateur, arrêtez SSH de KOReader, activez l’accès sans mot de passe, redémarrez SSH, cochez l’option correspondante dans l’application et reconnectez-vous.", "sending_file": "Envoi de {name} - {sent} sur {size}", "no_readable_files": "Aucun fichier de livre lisible n’a été sélectionné.", "connecting_secure": "Connexion sécurisée à {address}...", "create_books_failed": "Impossible de créer le dossier Books.", "transfer_cancelled": "Transfert annulé.", "connection_closed": "La connexion au Kindle s’est fermée de manière inattendue.", "sent_book_count": "{count} livres envoyés.",
    },
    "ja": {
        "language_tooltip": "言語を選択", "guide_downloads": "ガイドとダウンロード", "hero_eyebrow": "設定ではなく、本を", "hero_title": "1分以内に本を送信。", "hero_description": "ターミナル操作は不要です。KOReaderのパスワードなしオプションでWi-Fiペアリングするか、Kindleストレージが使えるときはUSBを利用できます。", "preparing_key": "Kindle用の秘密鍵を準備しています...", "on_kindle": "Kindle側の操作", "step_network": "同じローカルネットワーク、または相互に到達可能なネットワークを使用", "step_open": "KOReaderを開く", "step_ssh": "初回：パスワードなしを許可してSSHを開始", "your_kindle": "あなたのKindle", "device_hint": "到達可能なKindleアドレスを入力するか、空欄のままにして有効なプライベートネットワークを検索します。", "address_placeholder": "IP、ホスト名、host:port、または[IPv6]:port", "pair_usb": "USBでペアリング", "connect_find": "接続 / Kindleを検索", "no_password_label": "初回接続：KOReaderでパスワードなしログインを許可", "no_password_tooltip": "アプリは一度だけパスワードなしで接続し、このPCの公開鍵を登録して鍵ログインを確認します。Kindle側の設定は変更しません。", "firewall_help": "Windowsファイアウォールのヘルプ",
        "books_to_send": "送信する本", "book_count": "{count}冊 · {size}", "col_book": "本", "col_format": "形式", "col_size": "サイズ", "choose_books": "本を選択", "remove_selected": "選択項目を削除", "destination": "送信先：{path}", "ready_pairing": "ペアリングと検索の準備ができました。", "cancel": "キャンセル", "send_books": "本を送信", "footer": "バージョン {version}  ·  秘密鍵はこのPCにのみ保存  ·  終了後はKOReaderのSSHを停止", "drop_books": "ここに本をドロップ", "drop_subtitle": "またはクリックしてPDF、EPUB、MOBIなどのKOReader対応ファイルを選択",
        "usb_attention": "USBペアリングを確認してください：{error}", "usb_ready": "USBペアリングの準備ができました。安全に取り出し、KOReaderを開いてSSHサーバーを開始してください。", "paired_auto": "{roots} で自動ペアリングしました。秘密鍵はこのPCに残ります。", "usb_complete_eject": "USBペアリングが完了しました。Wi-Fiを使う前に安全に取り出してください。", "ready_previous": "以前使用したKindle（{address}）を検索できます。", "first_use_usb": "初回はKindleをUSBで一度接続して自動ペアリングするか、パスワードなしWi-Fiペアリングを使用してください。", "usb_pair_failed": "USBペアリングに失敗しました", "connect_usb_title": "KindleをUSBで接続", "usb_not_found": "マウントされたKOReader入りKindleストレージが見つかりません。\n\nKOReaderが開いている場合は先に終了してください。データ対応USBケーブルを接続し、Kindleドライブが表示されたら、もう一度USBでペアリングを押してください。\n\nKOReaderを開いたままにする場合は、パスワードなしのWi-Fiペアリングを使います。", "paired_status": "ペアリング済みです。安全に取り出し、KOReaderを開いて ツール → SSHサーバー を開始してください。", "key_installed": "公開鍵を {roots} に登録しました。パスワードは不要です。", "usb_complete": "USBペアリングが完了しました。", "kindle_paired": "Kindleをペアリングしました", "pairing_complete": "ペアリングが完了しました。\n\nKindleを安全に取り出して外し、同じWi-Fiに接続してKOReaderを開き、ツール > SSHサーバー を開始してください。",
        "firewall_dialog_title": "Windowsファイアウォールのヘルプ", "firewall_dialog": "Kindle Book Senderは外向きSSHクライアントです。通常、Windowsでは追加ルールなしで許可されます。\n\nTCPポート{port}の明示的な外向き許可ルールを作成しますか？WindowsのUAC管理者確認が表示されます。\n\nゲストWi-Fiの端末分離、誤ったアドレス、VPN経路、停止中のKindle SSHは解決できません。", "firewall_requested": "Windowsに外向きTCP {port}ルールを要求しました。UACを承認して再接続してください。", "firewall_failed": "Windowsで管理者権限のファイアウォール補助機能を開始できませんでした。", "looking": "ローカルネットワークでKindleを探しています...", "searching": "同じWi-Fi上のKOReader SSHを検索しています...", "connected": "Kindle接続済み - {address}", "bootstrap_success": "パスワードなしの初期設定に成功しました。このPCの公開鍵を登録し、鍵ログインを確認しました。", "key_verified": "このPCの秘密ペアリング鍵とKOReaderの構成を確認しました。", "kindle_found": "Kindleが見つかりました。本を追加して「本を送信」を押してください。", "choose_dialog": "KOReaderへ送る本を選択", "connecting": "{address} に接続しています...", "transfer_complete": "転送完了 · {count}冊を送信", "sent_size": "{size}を送信しました。KOReaderのファイル一覧を更新してください。", "books_sent": "本を送信しました", "books_sent_message": "{count}冊を送信しました。\n\nKOReaderの documents/Books にあります。", "action_needed": "操作が必要です", "cancelling": "キャンセルしています...",
        "supplied_invalid": "入力したKindleアドレスが無効です：{error}", "testing_supplied": "入力したアドレス {address} を最初に確認しています...", "no_private_network": "このPCにプライベートWi-FiまたはEthernetネットワークが見つかりません。", "searching_networks": "{count}個の有効なプライベートネットワークでKOReader SSHを検索しています...", "checking_possible": "{address} のKindle候補を確認しています...", "supplied_tested": "{address} を最初に確認しました：{error}", "endpoints_unverified": "ローカルSSHを{count}件見つけましたが、KOReader Kindleとして確認できませんでした。", "no_tcp_answer": "TCP 2222で応答する端末がありません。KOReader SSHが起動し、Wi-Fiの端末分離が無効であることを確認してください。", "new_computer_help": "新しいPCではKOReader SSHを停止し、パスワードなしログインを有効にしてSSHを再開し、アプリの同じオプションを選んで再接続してください。", "sending_file": "{name} を送信中 - {sent} / {size}", "no_readable_files": "読み取り可能な本が選択されていません。", "connecting_secure": "{address} に安全に接続しています...", "create_books_failed": "Booksフォルダーを作成できませんでした。", "transfer_cancelled": "転送をキャンセルしました。", "connection_closed": "Kindle接続が予期せず終了しました。", "sent_book_count": "{count}冊を送信しました。",
    },
    "ko": {
        "language_tooltip": "언어 선택", "guide_downloads": "가이드 및 다운로드", "hero_eyebrow": "설정 없이 책만", "hero_title": "1분 안에 책을 보내세요.", "hero_description": "터미널 명령이 필요 없습니다. KOReader의 비밀번호 없는 옵션으로 Wi-Fi 페어링하거나 Kindle 저장소가 보일 때 USB를 사용하세요.", "preparing_key": "Kindle 개인 키를 준비하는 중...", "on_kindle": "Kindle에서", "step_network": "같은 로컬 네트워크 또는 라우팅 가능한 네트워크 사용", "step_open": "KOReader 열기", "step_ssh": "처음 사용: 비밀번호 없는 로그인 허용 후 SSH 시작", "your_kindle": "내 Kindle", "device_hint": "연결 가능한 Kindle 주소를 입력하거나 비워 두어 활성 사설 인터페이스를 모두 검색하세요.", "address_placeholder": "IP, 호스트 이름, host:port 또는 [IPv6]:port", "pair_usb": "USB로 페어링", "connect_find": "연결 / Kindle 찾기", "no_password_label": "첫 연결: KOReader에서 비밀번호 없는 로그인 허용", "no_password_tooltip": "앱이 비밀번호 없이 한 번 접속하여 이 컴퓨터의 공개 키를 설치하고 키 로그인을 확인합니다. Kindle 설정은 변경하지 않습니다.", "firewall_help": "Windows 방화벽 도움말",
        "books_to_send": "보낼 책", "book_count": "책 {count}권 · {size}", "col_book": "책", "col_format": "형식", "col_size": "크기", "choose_books": "책 선택", "remove_selected": "선택 제거", "destination": "대상: {path}", "ready_pairing": "페어링 및 검색 준비 완료.", "cancel": "취소", "send_books": "책 보내기", "footer": "버전 {version}  ·  개인 키는 이 컴퓨터에만 보관  ·  완료 후 KOReader SSH 중지", "drop_books": "여기에 책을 놓으세요", "drop_subtitle": "또는 클릭하여 PDF, EPUB, MOBI 등 KOReader 파일 선택",
        "usb_attention": "USB 페어링 확인 필요: {error}", "usb_ready": "USB 페어링 준비 완료. 안전하게 꺼낸 뒤 KOReader를 열고 SSH 서버를 시작하세요.", "paired_auto": "{roots}에서 자동 페어링했습니다. 개인 키는 이 컴퓨터에 남습니다.", "usb_complete_eject": "USB 페어링 완료. Wi-Fi 사용 전에 안전하게 꺼내세요.", "ready_previous": "이전에 사용한 Kindle {address}을(를) 찾을 준비가 되었습니다.", "first_use_usb": "처음에는 Kindle을 USB로 한 번 연결해 자동 페어링하거나 비밀번호 없는 Wi-Fi 페어링을 사용하세요.", "usb_pair_failed": "USB 페어링 실패", "connect_usb_title": "Kindle을 USB로 연결", "usb_not_found": "마운트된 KOReader Kindle 저장소를 찾지 못했습니다.\n\nKOReader가 열려 있으면 먼저 종료하세요. 데이터 USB 케이블을 연결하고 Kindle 드라이브가 나타날 때까지 기다린 다음 USB로 페어링을 다시 누르세요.\n\nKOReader를 계속 열어 두려면 비밀번호 없는 Wi-Fi 페어링을 사용하세요.", "paired_status": "페어링됨. 안전하게 꺼내고 KOReader를 연 뒤 도구 → SSH 서버를 시작하세요.", "key_installed": "{roots}에 공개 키를 설치했습니다. 비밀번호가 필요 없습니다.", "usb_complete": "USB 페어링 완료.", "kindle_paired": "Kindle 페어링 완료", "pairing_complete": "페어링이 완료되었습니다.\n\nKindle을 안전하게 꺼내 분리하고 같은 Wi-Fi에 연결한 뒤 KOReader에서 도구 > SSH 서버를 시작하세요.",
        "firewall_dialog_title": "Windows 방화벽 도움말", "firewall_dialog": "Kindle Book Sender는 아웃바운드 SSH 클라이언트이며 Windows는 보통 별도 규칙 없이 허용합니다.\n\nTCP 포트 {port}에 명시적 아웃바운드 허용 규칙을 만들까요? Windows UAC 관리자 창이 표시됩니다.\n\n게스트 Wi-Fi 격리, 잘못된 주소, VPN 라우팅 또는 중지된 Kindle SSH는 해결할 수 없습니다.", "firewall_requested": "Windows에 아웃바운드 TCP {port} 규칙을 요청했습니다. UAC를 승인한 뒤 다시 연결하세요.", "firewall_failed": "Windows가 관리자 권한 방화벽 도우미를 시작하지 못했습니다.", "looking": "로컬 네트워크에서 Kindle을 찾는 중...", "searching": "같은 Wi-Fi에서 KOReader SSH를 검색하는 중...", "connected": "Kindle 연결됨 - {address}", "bootstrap_success": "비밀번호 없는 초기 설정에 성공했습니다. 이 컴퓨터의 공개 키를 설치하고 키 로그인을 확인했습니다.", "key_verified": "이 컴퓨터의 개인 페어링 키와 KOReader 설치를 확인했습니다.", "kindle_found": "Kindle을 찾았습니다. 책을 추가한 뒤 책 보내기를 누르세요.", "choose_dialog": "KOReader로 보낼 책 선택", "connecting": "{address}에 연결 중...", "transfer_complete": "전송 완료 · 책 {count}권 전송", "sent_size": "{size} 전송됨. KOReader 파일 브라우저를 새로 고치세요.", "books_sent": "책 전송 완료", "books_sent_message": "책 {count}권을 전송했습니다.\n\nKOReader의 documents/Books에서 찾을 수 있습니다.", "action_needed": "조치 필요", "cancelling": "취소 중...",
        "supplied_invalid": "입력한 Kindle 주소가 올바르지 않습니다: {error}", "testing_supplied": "입력한 주소 {address}을(를) 먼저 확인하는 중...", "no_private_network": "이 컴퓨터에서 사설 Wi-Fi 또는 Ethernet 네트워크를 찾지 못했습니다.", "searching_networks": "활성 사설 네트워크 {count}개에서 KOReader SSH 검색 중...", "checking_possible": "{address}의 Kindle 후보 확인 중...", "supplied_tested": "{address}을(를) 먼저 확인했습니다: {error}", "endpoints_unverified": "로컬 SSH 서비스 {count}개를 찾았지만 KOReader Kindle로 확인되지 않았습니다.", "no_tcp_answer": "TCP 2222에 응답한 로컬 장치가 없습니다. KOReader SSH가 시작되었고 Wi-Fi가 클라이언트를 격리하지 않는지 확인하세요.", "new_computer_help": "새 컴퓨터에서는 KOReader SSH를 중지하고 비밀번호 없는 로그인을 켠 뒤 SSH를 다시 시작하고 앱의 해당 옵션을 선택해 재연결하세요.", "sending_file": "{name} 전송 중 - {sent} / {size}", "no_readable_files": "읽을 수 있는 책 파일을 선택하지 않았습니다.", "connecting_secure": "{address}에 안전하게 연결 중...", "create_books_failed": "Books 폴더를 만들 수 없습니다.", "transfer_cancelled": "전송이 취소되었습니다.", "connection_closed": "Kindle 연결이 예기치 않게 종료되었습니다.", "sent_book_count": "책 {count}권 전송됨.",
    },
    "vi": {
        "language_tooltip": "Chọn ngôn ngữ", "guide_downloads": "Hướng dẫn và tải xuống", "hero_eyebrow": "CHỈ GỬI SÁCH, KHÔNG CẦN CÀI ĐẶT", "hero_title": "Gửi sách trong chưa đầy một phút.", "hero_description": "Không cần lệnh terminal. Ghép đôi qua Wi-Fi bằng tùy chọn không mật khẩu của KOReader, hoặc dùng USB khi bộ nhớ Kindle khả dụng.", "preparing_key": "Đang chuẩn bị khóa Kindle riêng...", "on_kindle": "Trên Kindle", "step_network": "Dùng cùng mạng nội bộ hoặc một mạng có định tuyến", "step_open": "Mở KOReader", "step_ssh": "Lần đầu: cho phép không mật khẩu rồi khởi động SSH", "your_kindle": "Kindle của bạn", "device_hint": "Nhập địa chỉ Kindle có thể truy cập, hoặc để trống để quét mọi giao diện mạng riêng đang hoạt động.", "address_placeholder": "IP, tên máy, host:cổng hoặc [IPv6]:cổng", "pair_usb": "Ghép đôi qua USB", "connect_find": "Kết nối / tìm Kindle", "no_password_label": "Kết nối đầu tiên: KOReader cho phép đăng nhập không mật khẩu", "no_password_tooltip": "Ứng dụng sẽ dùng quyền truy cập không mật khẩu một lần, cài khóa công khai của máy này và xác minh đăng nhập bằng khóa. Ứng dụng không thay đổi cài đặt Kindle.", "firewall_help": "Trợ giúp tường lửa Windows",
        "books_to_send": "Sách cần gửi", "book_count": "{count} sách · {size}", "col_book": "Sách", "col_format": "Định dạng", "col_size": "Kích thước", "choose_books": "Chọn sách", "remove_selected": "Bỏ mục đã chọn", "destination": "Đích: {path}", "ready_pairing": "Sẵn sàng ghép đôi và tìm kiếm.", "cancel": "Hủy", "send_books": "Gửi sách", "footer": "Phiên bản {version}  ·  Khóa riêng chỉ ở trên máy này  ·  Dừng SSH của KOReader khi hoàn tất", "drop_books": "Thả sách vào đây", "drop_subtitle": "hoặc bấm để chọn PDF, EPUB, MOBI và các tệp KOReader khác",
        "usb_attention": "Ghép đôi USB cần chú ý: {error}", "usb_ready": "Ghép đôi USB đã sẵn sàng. Tháo an toàn, mở KOReader và khởi động máy chủ SSH.", "paired_auto": "Đã tự động ghép đôi tại {roots}. Khóa riêng vẫn ở trên máy này.", "usb_complete_eject": "Ghép đôi USB hoàn tất. Hãy tháo an toàn trước khi dùng Wi-Fi.", "ready_previous": "Sẵn sàng tìm Kindle đã dùng trước đây tại {address}.", "first_use_usb": "Lần đầu: kết nối Kindle qua USB một lần để tự động ghép đôi, hoặc dùng ghép đôi Wi-Fi không mật khẩu.", "usb_pair_failed": "Ghép đôi USB thất bại", "connect_usb_title": "Kết nối Kindle qua USB", "usb_not_found": "Không tìm thấy bộ nhớ Kindle có KOReader đang được gắn.\n\nNếu KOReader đang mở, hãy thoát trước. Cắm cáp USB dữ liệu, chờ ổ Kindle xuất hiện rồi bấm Ghép đôi qua USB lần nữa.\n\nĐể giữ KOReader mở, hãy dùng ghép đôi Wi-Fi không mật khẩu.", "paired_status": "Đã ghép đôi. Tháo an toàn, mở KOReader rồi khởi động Công cụ → Máy chủ SSH.", "key_installed": "Đã cài khóa công khai trên {roots}. Không cần mật khẩu.", "usb_complete": "Ghép đôi USB hoàn tất.", "kindle_paired": "Đã ghép đôi Kindle", "pairing_complete": "Ghép đôi đã hoàn tất.\n\nTháo Kindle an toàn, kết nối vào cùng Wi-Fi, mở KOReader và khởi động Công cụ > Máy chủ SSH.",
        "firewall_dialog_title": "Trợ giúp tường lửa Windows", "firewall_dialog": "Kindle Book Sender là ứng dụng SSH kết nối ra ngoài. Windows thường cho phép mà không cần quy tắc.\n\nTạo quy tắc cho phép TCP cổng {port}? Windows sẽ hiện yêu cầu quản trị UAC.\n\nViệc này không sửa được cô lập thiết bị Wi-Fi, sai địa chỉ, định tuyến VPN hoặc SSH Kindle đang dừng.", "firewall_requested": "Windows đã yêu cầu quy tắc TCP ra ngoài cho cổng {port}. Chấp nhận UAC rồi kết nối lại.", "firewall_failed": "Windows không thể khởi động trợ lý tường lửa với quyền quản trị.", "looking": "Đang tìm Kindle trên mạng nội bộ...", "searching": "Đang tìm SSH của KOReader trên cùng Wi-Fi...", "connected": "Đã kết nối Kindle - {address}", "bootstrap_success": "Thiết lập không mật khẩu thành công. Khóa công khai của máy này đã được cài và đăng nhập bằng khóa đã được xác minh.", "key_verified": "Đã xác minh bằng khóa ghép đôi riêng của máy này và bản cài KOReader.", "kindle_found": "Đã tìm thấy Kindle. Thêm sách rồi bấm Gửi sách.", "choose_dialog": "Chọn sách để gửi đến KOReader", "connecting": "Đang kết nối tới {address}...", "transfer_complete": "Truyền hoàn tất · đã gửi {count} sách", "sent_size": "Đã gửi {size}. Hãy làm mới trình duyệt tệp KOReader.", "books_sent": "Đã gửi sách", "books_sent_message": "Đã gửi thành công {count} sách.\n\nTìm chúng trong documents/Books của KOReader.", "action_needed": "Cần thao tác", "cancelling": "Đang hủy...",
        "supplied_invalid": "Địa chỉ Kindle đã nhập không hợp lệ: {error}", "testing_supplied": "Đang thử địa chỉ {address} trước...", "no_private_network": "Không tìm thấy mạng Wi-Fi hoặc Ethernet riêng trên máy này.", "searching_networks": "Đang tìm SSH KOReader trên {count} mạng riêng đang hoạt động...", "checking_possible": "Đang kiểm tra Kindle có thể có tại {address}...", "supplied_tested": "Đã thử địa chỉ {address} trước: {error}", "endpoints_unverified": "Tìm thấy {count} dịch vụ SSH nội bộ nhưng chưa dịch vụ nào được xác minh là Kindle KOReader này.", "no_tcp_answer": "Không thiết bị nội bộ nào phản hồi TCP 2222. Xác nhận SSH KOReader đã chạy và Wi-Fi không cô lập thiết bị.", "new_computer_help": "Trên máy mới, dừng SSH KOReader, bật đăng nhập không mật khẩu, khởi động lại SSH, chọn tùy chọn tương ứng trong ứng dụng rồi kết nối lại.", "sending_file": "Đang gửi {name} - {sent} / {size}", "no_readable_files": "Chưa chọn tệp sách có thể đọc.", "connecting_secure": "Đang kết nối an toàn tới {address}...", "create_books_failed": "Không thể tạo thư mục Books.", "transfer_cancelled": "Đã hủy truyền.", "connection_closed": "Kết nối Kindle bị đóng ngoài dự kiến.", "sent_book_count": "Đã gửi {count} sách.",
    },
    "zh-Hans": {
        "language_tooltip": "选择语言", "guide_downloads": "指南与下载", "hero_eyebrow": "只管传书，无需配置", "hero_title": "不到一分钟，把书传到 Kindle。", "hero_description": "无需终端命令。可使用 KOReader 的免密码选项通过 Wi-Fi 配对，也可在 Kindle 存储可见时通过 USB 配对。", "preparing_key": "正在准备 Kindle 私钥……", "on_kindle": "在 Kindle 上", "step_network": "使用同一局域网，或可路由互通的本地网络", "step_open": "打开 KOReader", "step_ssh": "首次使用：允许免密码登录，然后启动 SSH", "your_kindle": "你的 Kindle", "device_hint": "输入任意可访问的 Kindle 地址，或留空以扫描所有活动的私有网络接口。", "address_placeholder": "IP、主机名、host:端口 或 [IPv6]:端口", "pair_usb": "通过 USB 配对", "connect_find": "连接 / 查找 Kindle", "no_password_label": "首次连接：KOReader 已允许免密码登录", "no_password_tooltip": "应用会使用一次免密码访问，安装此电脑的公钥并验证密钥登录。它不会更改 Kindle 上的设置。", "firewall_help": "Windows 防火墙帮助",
        "books_to_send": "待发送图书", "book_count": "{count} 本书 · {size}", "col_book": "图书", "col_format": "格式", "col_size": "大小", "choose_books": "选择图书", "remove_selected": "移除所选", "destination": "目标：{path}", "ready_pairing": "已准备好配对和查找。", "cancel": "取消", "send_books": "发送图书", "footer": "版本 {version}  ·  私钥仅保留在此电脑  ·  完成后请关闭 KOReader SSH", "drop_books": "把图书拖到这里", "drop_subtitle": "或点击选择 PDF、EPUB、MOBI 及其他 KOReader 文件",
        "usb_attention": "USB 配对需要处理：{error}", "usb_ready": "USB 配对已就绪。请安全弹出，打开 KOReader 并启动 SSH 服务器。", "paired_auto": "已在 {roots} 自动配对。私钥仍保留在此电脑。", "usb_complete_eject": "USB 配对完成。使用 Wi-Fi 前请安全弹出。", "ready_previous": "已准备查找上次使用的 Kindle：{address}。", "first_use_usb": "首次使用：通过 USB 连接一次以自动配对，或使用免密码 Wi-Fi 配对。", "usb_pair_failed": "USB 配对失败", "connect_usb_title": "通过 USB 连接 Kindle", "usb_not_found": "未找到已挂载且包含 KOReader 的 Kindle 存储。\n\n如果 KOReader 正在运行，请先退出。连接可传输数据的 USB 线，等待 Kindle 磁盘出现，然后再次点击“通过 USB 配对”。\n\n如需保持 KOReader 运行，请改用免密码 Wi-Fi 配对。", "paired_status": "已配对。请安全弹出，打开 KOReader，然后启动 工具 → SSH 服务器。", "key_installed": "已在 {roots} 安装公钥，无需密码。", "usb_complete": "USB 配对完成。", "kindle_paired": "Kindle 已配对", "pairing_complete": "配对已完成。\n\n请安全弹出并拔下 Kindle，将其连接到同一 Wi-Fi，打开 KOReader，然后启动 工具 > SSH 服务器。",
        "firewall_dialog_title": "Windows 防火墙帮助", "firewall_dialog": "Kindle Book Sender 是向外连接的 SSH 客户端，Windows 通常无需额外规则即可允许。\n\n是否为 TCP 端口 {port} 创建明确的出站允许规则？Windows 将显示 UAC 管理员提示。\n\n这无法解决访客 Wi-Fi/客户端隔离、地址错误、VPN 路由或 Kindle SSH 未启动。", "firewall_requested": "Windows 已请求添加出站 TCP {port} 防火墙规则。批准 UAC 提示后请重新连接。", "firewall_failed": "Windows 无法启动提升权限的防火墙助手。", "looking": "正在局域网上查找 Kindle……", "searching": "正在同一 Wi-Fi 上搜索 KOReader SSH……", "connected": "Kindle 已连接 - {address}", "bootstrap_success": "免密码初始化成功。已安装此电脑的公钥，并验证了密钥登录。", "key_verified": "已通过此电脑的私有配对密钥和 KOReader 安装进行验证。", "kindle_found": "已找到 Kindle。添加图书，然后点击“发送图书”。", "choose_dialog": "选择要发送到 KOReader 的图书", "connecting": "正在连接 {address}……", "transfer_complete": "传输完成 · 已发送 {count} 本书", "sent_size": "已发送 {size}。请刷新 KOReader 文件浏览器。", "books_sent": "图书已发送", "books_sent_message": "已成功发送 {count} 本书。\n\n可在 KOReader 的 documents/Books 中找到。", "action_needed": "需要处理", "cancelling": "正在取消……",
        "supplied_invalid": "输入的 Kindle 地址无效：{error}", "testing_supplied": "正在优先测试所填地址 {address}……", "no_private_network": "此电脑上未找到私有 Wi-Fi 或以太网网络。", "searching_networks": "正在 {count} 个活动私有网络中搜索 KOReader SSH……", "checking_possible": "正在检查 {address} 处可能的 Kindle……", "supplied_tested": "已优先测试地址 {address}：{error}", "endpoints_unverified": "找到了 {count} 个本地 SSH 服务，但都未验证为此 KOReader Kindle。", "no_tcp_answer": "没有本地设备响应 TCP 2222。请确认 KOReader SSH 已启动，且 Wi-Fi 未隔离客户端。", "new_computer_help": "在新电脑上，请停止 KOReader SSH，启用免密码登录，再启动 SSH，勾选应用中的免密码选项并重新连接。", "sending_file": "正在发送 {name} - {sent} / {size}", "no_readable_files": "未选择可读取的图书文件。", "connecting_secure": "正在安全连接 {address}……", "create_books_failed": "无法创建 Books 文件夹。", "transfer_cancelled": "传输已取消。", "connection_closed": "Kindle 连接意外关闭。", "sent_book_count": "已发送 {count} 本书。",
    },
    "zh-Hant": {
        "language_tooltip": "選擇語言", "guide_downloads": "指南與下載", "hero_eyebrow": "只管傳書，無需設定", "hero_title": "不到一分鐘，把書傳到 Kindle。", "hero_description": "無需終端指令。可使用 KOReader 的免密碼選項透過 Wi-Fi 配對，也可在 Kindle 儲存空間可見時透過 USB 配對。", "preparing_key": "正在準備 Kindle 私密金鑰……", "on_kindle": "在 Kindle 上", "step_network": "使用同一區域網路，或可路由互通的本地網路", "step_open": "開啟 KOReader", "step_ssh": "首次使用：允許免密碼登入，然後啟動 SSH", "your_kindle": "你的 Kindle", "device_hint": "輸入任意可存取的 Kindle 位址，或留空以掃描所有活動的私人網路介面。", "address_placeholder": "IP、主機名稱、host:連接埠 或 [IPv6]:連接埠", "pair_usb": "透過 USB 配對", "connect_find": "連線 / 尋找 Kindle", "no_password_label": "首次連線：KOReader 已允許免密碼登入", "no_password_tooltip": "應用程式會使用一次免密碼存取，安裝此電腦的公開金鑰並驗證金鑰登入。它不會變更 Kindle 上的設定。", "firewall_help": "Windows 防火牆說明",
        "books_to_send": "待傳送書籍", "book_count": "{count} 本書 · {size}", "col_book": "書籍", "col_format": "格式", "col_size": "大小", "choose_books": "選擇書籍", "remove_selected": "移除所選", "destination": "目的地：{path}", "ready_pairing": "已準備好配對和尋找。", "cancel": "取消", "send_books": "傳送書籍", "footer": "版本 {version}  ·  私密金鑰僅保留在此電腦  ·  完成後請關閉 KOReader SSH", "drop_books": "把書籍拖到這裡", "drop_subtitle": "或按一下選擇 PDF、EPUB、MOBI 及其他 KOReader 檔案",
        "usb_attention": "USB 配對需要處理：{error}", "usb_ready": "USB 配對已就緒。請安全退出，開啟 KOReader 並啟動 SSH 伺服器。", "paired_auto": "已在 {roots} 自動配對。私密金鑰仍保留在此電腦。", "usb_complete_eject": "USB 配對完成。使用 Wi-Fi 前請安全退出。", "ready_previous": "已準備尋找上次使用的 Kindle：{address}。", "first_use_usb": "首次使用：透過 USB 連接一次以自動配對，或使用免密碼 Wi-Fi 配對。", "usb_pair_failed": "USB 配對失敗", "connect_usb_title": "透過 USB 連接 Kindle", "usb_not_found": "找不到已掛載且包含 KOReader 的 Kindle 儲存空間。\n\n如果 KOReader 正在執行，請先退出。連接可傳輸資料的 USB 線，等待 Kindle 磁碟出現，然後再次按一下「透過 USB 配對」。\n\n如需保持 KOReader 執行，請改用免密碼 Wi-Fi 配對。", "paired_status": "已配對。請安全退出，開啟 KOReader，然後啟動 工具 → SSH 伺服器。", "key_installed": "已在 {roots} 安裝公開金鑰，無需密碼。", "usb_complete": "USB 配對完成。", "kindle_paired": "Kindle 已配對", "pairing_complete": "配對已完成。\n\n請安全退出並拔下 Kindle，將其連接到同一 Wi-Fi，開啟 KOReader，然後啟動 工具 > SSH 伺服器。",
        "firewall_dialog_title": "Windows 防火牆說明", "firewall_dialog": "Kindle Book Sender 是向外連線的 SSH 用戶端，Windows 通常無需額外規則即可允許。\n\n是否為 TCP 連接埠 {port} 建立明確的輸出允許規則？Windows 將顯示 UAC 管理員提示。\n\n這無法解決訪客 Wi-Fi/用戶端隔離、位址錯誤、VPN 路由或 Kindle SSH 未啟動。", "firewall_requested": "Windows 已要求新增輸出 TCP {port} 防火牆規則。批准 UAC 提示後請重新連線。", "firewall_failed": "Windows 無法啟動提升權限的防火牆助手。", "looking": "正在區域網路上尋找 Kindle……", "searching": "正在同一 Wi-Fi 上搜尋 KOReader SSH……", "connected": "Kindle 已連線 - {address}", "bootstrap_success": "免密碼初始化成功。已安裝此電腦的公開金鑰，並驗證了金鑰登入。", "key_verified": "已透過此電腦的私密配對金鑰和 KOReader 安裝進行驗證。", "kindle_found": "已找到 Kindle。加入書籍，然後按一下「傳送書籍」。", "choose_dialog": "選擇要傳送到 KOReader 的書籍", "connecting": "正在連線 {address}……", "transfer_complete": "傳輸完成 · 已傳送 {count} 本書", "sent_size": "已傳送 {size}。請重新整理 KOReader 檔案瀏覽器。", "books_sent": "書籍已傳送", "books_sent_message": "已成功傳送 {count} 本書。\n\n可在 KOReader 的 documents/Books 中找到。", "action_needed": "需要處理", "cancelling": "正在取消……",
        "supplied_invalid": "輸入的 Kindle 位址無效：{error}", "testing_supplied": "正在優先測試所填位址 {address}……", "no_private_network": "此電腦上找不到私人 Wi-Fi 或乙太網路。", "searching_networks": "正在 {count} 個活動私人網路中搜尋 KOReader SSH……", "checking_possible": "正在檢查 {address} 處可能的 Kindle……", "supplied_tested": "已優先測試位址 {address}：{error}", "endpoints_unverified": "找到了 {count} 個本地 SSH 服務，但都未驗證為此 KOReader Kindle。", "no_tcp_answer": "沒有本地裝置回應 TCP 2222。請確認 KOReader SSH 已啟動，且 Wi-Fi 未隔離用戶端。", "new_computer_help": "在新電腦上，請停止 KOReader SSH，啟用免密碼登入，再啟動 SSH，勾選應用程式中的免密碼選項並重新連線。", "sending_file": "正在傳送 {name} - {sent} / {size}", "no_readable_files": "未選擇可讀取的書籍檔案。", "connecting_secure": "正在安全連線 {address}……", "create_books_failed": "無法建立 Books 資料夾。", "transfer_cancelled": "傳輸已取消。", "connection_closed": "Kindle 連線意外關閉。", "sent_book_count": "已傳送 {count} 本書。",
    },
    "de": {
        "language_tooltip": "Sprache wählen", "guide_downloads": "Anleitung & Downloads", "hero_eyebrow": "BÜCHER STATT EINRICHTUNG", "hero_title": "Sende ein Buch in unter einer Minute.", "hero_description": "Keine Terminalbefehle. Kopple per WLAN mit der passwortlosen KOReader-Option oder nutze USB, wenn der Kindle-Speicher verfügbar ist.", "preparing_key": "Privater Kindle-Schlüssel wird vorbereitet...", "on_kindle": "Auf deinem Kindle", "step_network": "Dasselbe lokale oder ein anderes geroutetes Netzwerk verwenden", "step_open": "KOReader öffnen", "step_ssh": "Erste Nutzung: Anmeldung ohne Passwort erlauben, dann SSH starten", "your_kindle": "Dein Kindle", "device_hint": "Gib eine erreichbare Kindle-Adresse ein oder lasse das Feld leer, um alle aktiven privaten Schnittstellen zu durchsuchen.", "address_placeholder": "IP, Hostname, host:Port oder [IPv6]:Port", "pair_usb": "Über USB koppeln", "connect_find": "Verbinden / Kindle finden", "no_password_label": "Erste Verbindung: KOReader erlaubt Anmeldung ohne Passwort", "no_password_tooltip": "Die App nutzt einmalig den passwortlosen Zugriff, installiert den öffentlichen Schlüssel dieses Computers und prüft die Schlüsselanmeldung. Die Kindle-Einstellung wird nicht geändert.", "firewall_help": "Windows-Firewall-Hilfe",
        "books_to_send": "Zu sendende Bücher", "book_count": "{count} Bücher · {size}", "col_book": "Buch", "col_format": "Format", "col_size": "Größe", "choose_books": "Bücher auswählen", "remove_selected": "Auswahl entfernen", "destination": "Ziel: {path}", "ready_pairing": "Bereit zum Koppeln und Suchen.", "cancel": "Abbrechen", "send_books": "Bücher senden", "footer": "Version {version}  ·  Privater Schlüssel bleibt auf diesem Computer  ·  KOReader-SSH danach stoppen", "drop_books": "Bücher hier ablegen", "drop_subtitle": "oder klicken, um PDF, EPUB, MOBI und weitere KOReader-Dateien auszuwählen",
        "usb_attention": "USB-Kopplung benötigt Aufmerksamkeit: {error}", "usb_ready": "USB-Kopplung ist bereit. Sicher auswerfen, KOReader öffnen und den SSH-Server starten.", "paired_auto": "Automatisch auf {roots} gekoppelt. Der private Schlüssel bleibt auf diesem Computer.", "usb_complete_eject": "USB-Kopplung abgeschlossen. Vor WLAN-Nutzung sicher auswerfen.", "ready_previous": "Bereit, den zuvor verwendeten Kindle unter {address} zu suchen.", "first_use_usb": "Erste Nutzung: Kindle einmal per USB zur automatischen Kopplung verbinden oder passwortlos per WLAN koppeln.", "usb_pair_failed": "USB-Kopplung fehlgeschlagen", "connect_usb_title": "Kindle über USB verbinden", "usb_not_found": "Kein eingebundener Kindle-Speicher mit KOReader gefunden.\n\nFalls KOReader geöffnet ist, beende ihn zuerst. Schließe ein USB-Datenkabel an, warte auf das Kindle-Laufwerk und klicke erneut auf Über USB koppeln.\n\nUm KOReader geöffnet zu lassen, verwende die passwortlose WLAN-Kopplung.", "paired_status": "Gekoppelt. Sicher auswerfen, KOReader öffnen und Werkzeuge → SSH-Server starten.", "key_installed": "Öffentlicher Schlüssel auf {roots} installiert. Kein Passwort erforderlich.", "usb_complete": "USB-Kopplung abgeschlossen.", "kindle_paired": "Kindle gekoppelt", "pairing_complete": "Die Kopplung ist abgeschlossen.\n\nKindle sicher auswerfen und trennen, mit demselben WLAN verbinden, KOReader öffnen und Werkzeuge > SSH-Server starten.",
        "firewall_dialog_title": "Windows-Firewall-Hilfe", "firewall_dialog": "Kindle Book Sender ist ein ausgehender SSH-Client. Windows erlaubt dies normalerweise ohne Regel.\n\nEine ausdrückliche ausgehende Regel für TCP-Port {port} erstellen? Windows zeigt eine UAC-Administratorabfrage.\n\nDies behebt keine WLAN-Client-Isolierung, falsche Adresse, VPN-Routen oder einen gestoppten Kindle-SSH-Server.", "firewall_requested": "Windows hat eine ausgehende TCP-{port}-Regel angefordert. UAC bestätigen und erneut verbinden.", "firewall_failed": "Windows konnte den erhöhten Firewall-Helfer nicht starten.", "looking": "Kindle wird im lokalen Netzwerk gesucht...", "searching": "KOReader-SSH wird im selben WLAN gesucht...", "connected": "Kindle verbunden - {address}", "bootstrap_success": "Passwortlose Ersteinrichtung erfolgreich. Der öffentliche Schlüssel dieses Computers wurde installiert und die Schlüsselanmeldung geprüft.", "key_verified": "Mit dem privaten Kopplungsschlüssel dieses Computers und der KOReader-Installation verifiziert.", "kindle_found": "Kindle gefunden. Bücher hinzufügen und auf Bücher senden klicken.", "choose_dialog": "Bücher zum Senden an KOReader auswählen", "connecting": "Verbindung mit {address}...", "transfer_complete": "Übertragung abgeschlossen · {count} Bücher gesendet", "sent_size": "{size} gesendet. KOReader-Dateibrowser aktualisieren.", "books_sent": "Bücher gesendet", "books_sent_message": "{count} Bücher wurden erfolgreich gesendet.\n\nSie befinden sich in documents/Books in KOReader.", "action_needed": "Aktion erforderlich", "cancelling": "Wird abgebrochen...",
        "supplied_invalid": "Die eingegebene Kindle-Adresse ist ungültig: {error}", "testing_supplied": "Die eingegebene Adresse {address} wird zuerst geprüft...", "no_private_network": "Auf diesem Computer wurde kein privates WLAN- oder Ethernet-Netzwerk gefunden.", "searching_networks": "{count} aktive private Netzwerke werden nach KOReader-SSH durchsucht...", "checking_possible": "Möglicher Kindle unter {address} wird geprüft...", "supplied_tested": "{address} wurde zuerst geprüft: {error}", "endpoints_unverified": "{count} lokale SSH-Dienste gefunden, aber keiner als dieser KOReader-Kindle verifiziert.", "no_tcp_answer": "Kein lokales Gerät antwortete auf TCP 2222. Prüfe, ob KOReader-SSH läuft und das WLAN Clients nicht isoliert.", "new_computer_help": "Auf einem neuen Computer KOReader-SSH stoppen, Anmeldung ohne Passwort aktivieren, SSH neu starten, die App-Option markieren und erneut verbinden.", "sending_file": "{name} wird gesendet - {sent} von {size}", "no_readable_files": "Keine lesbaren Buchdateien ausgewählt.", "connecting_secure": "Sichere Verbindung mit {address}...", "create_books_failed": "Der Ordner Books konnte nicht erstellt werden.", "transfer_cancelled": "Übertragung abgebrochen.", "connection_closed": "Die Kindle-Verbindung wurde unerwartet geschlossen.", "sent_book_count": "{count} Bücher gesendet.",
    },
    "ru": {
        "language_tooltip": "Выбрать язык", "guide_downloads": "Руководство и загрузки", "hero_eyebrow": "КНИГИ БЕЗ СЛОЖНОЙ НАСТРОЙКИ", "hero_title": "Отправьте книгу меньше чем за минуту.", "hero_description": "Команды терминала не нужны. Выполните сопряжение по Wi-Fi с опцией KOReader без пароля или используйте USB, когда хранилище Kindle доступно.", "preparing_key": "Подготовка закрытого ключа Kindle...", "on_kindle": "На Kindle", "step_network": "Используйте ту же локальную сеть или другую сеть с маршрутом", "step_open": "Откройте KOReader", "step_ssh": "Первый запуск: разрешите вход без пароля и запустите SSH", "your_kindle": "Ваш Kindle", "device_hint": "Введите доступный адрес Kindle или оставьте поле пустым для поиска во всех активных частных интерфейсах.", "address_placeholder": "IP, имя узла, host:порт или [IPv6]:порт", "pair_usb": "Сопряжение по USB", "connect_find": "Подключить / найти Kindle", "no_password_label": "Первое подключение: KOReader разрешает вход без пароля", "no_password_tooltip": "Приложение один раз войдёт без пароля, установит открытый ключ этого компьютера и проверит вход по ключу. Настройка Kindle не будет изменена.", "firewall_help": "Помощь с брандмауэром Windows",
        "books_to_send": "Книги для отправки", "book_count": "{count} книг · {size}", "col_book": "Книга", "col_format": "Формат", "col_size": "Размер", "choose_books": "Выбрать книги", "remove_selected": "Удалить выбранное", "destination": "Назначение: {path}", "ready_pairing": "Готово к сопряжению и поиску.", "cancel": "Отмена", "send_books": "Отправить книги", "footer": "Версия {version}  ·  Закрытый ключ остаётся на этом компьютере  ·  После работы остановите SSH KOReader", "drop_books": "Перетащите книги сюда", "drop_subtitle": "или нажмите, чтобы выбрать PDF, EPUB, MOBI и другие файлы KOReader",
        "usb_attention": "Сопряжение по USB требует внимания: {error}", "usb_ready": "Сопряжение по USB готово. Безопасно извлеките Kindle, откройте KOReader и запустите SSH-сервер.", "paired_auto": "Автоматическое сопряжение выполнено на {roots}. Закрытый ключ остаётся на этом компьютере.", "usb_complete_eject": "Сопряжение по USB завершено. Безопасно извлеките устройство перед использованием Wi-Fi.", "ready_previous": "Готово к поиску ранее использованного Kindle по адресу {address}.", "first_use_usb": "При первом запуске один раз подключите Kindle по USB для автоматического сопряжения или используйте Wi-Fi без пароля.", "usb_pair_failed": "Сбой сопряжения по USB", "connect_usb_title": "Подключите Kindle по USB", "usb_not_found": "Подключённое хранилище Kindle с KOReader не найдено.\n\nЕсли KOReader открыт, сначала выйдите из него. Подключите USB-кабель для данных, дождитесь появления диска Kindle и снова нажмите «Сопряжение по USB».\n\nЧтобы оставить KOReader открытым, используйте сопряжение по Wi-Fi без пароля.", "paired_status": "Сопряжение выполнено. Безопасно извлеките устройство, откройте KOReader и запустите Инструменты → SSH-сервер.", "key_installed": "Открытый ключ установлен на {roots}. Пароль не требуется.", "usb_complete": "Сопряжение по USB завершено.", "kindle_paired": "Kindle сопряжён", "pairing_complete": "Сопряжение завершено.\n\nБезопасно извлеките и отключите Kindle, подключите его к той же сети Wi-Fi, откройте KOReader и запустите Инструменты > SSH-сервер.",
        "firewall_dialog_title": "Помощь с брандмауэром Windows", "firewall_dialog": "Kindle Book Sender — исходящий SSH-клиент. Обычно Windows разрешает это без отдельного правила.\n\nСоздать явное исходящее правило для TCP-порта {port}? Windows покажет запрос администратора UAC.\n\nЭто не исправит изоляцию клиентов Wi-Fi, неверный адрес, маршрутизацию VPN или остановленный SSH Kindle.", "firewall_requested": "Windows запросила исходящее правило TCP {port}. Подтвердите UAC и подключитесь снова.", "firewall_failed": "Windows не удалось запустить помощник брандмауэра с повышенными правами.", "looking": "Поиск Kindle в локальной сети...", "searching": "Поиск SSH KOReader в той же сети Wi-Fi...", "connected": "Kindle подключён - {address}", "bootstrap_success": "Настройка без пароля выполнена. Открытый ключ этого компьютера установлен, вход по ключу проверен.", "key_verified": "Проверено закрытым ключом сопряжения этого компьютера и установкой KOReader.", "kindle_found": "Kindle найден. Добавьте книги и нажмите «Отправить книги».", "choose_dialog": "Выберите книги для отправки в KOReader", "connecting": "Подключение к {address}...", "transfer_complete": "Передача завершена · отправлено книг: {count}", "sent_size": "Отправлено {size}. Обновите файловый браузер KOReader.", "books_sent": "Книги отправлены", "books_sent_message": "Успешно отправлено книг: {count}.\n\nОни находятся в documents/Books в KOReader.", "action_needed": "Требуется действие", "cancelling": "Отмена...",
        "supplied_invalid": "Указан неверный адрес Kindle: {error}", "testing_supplied": "Сначала проверяется указанный адрес {address}...", "no_private_network": "На этом компьютере не найдена частная сеть Wi-Fi или Ethernet.", "searching_networks": "Поиск SSH KOReader в активных частных сетях: {count}...", "checking_possible": "Проверка возможного Kindle по адресу {address}...", "supplied_tested": "Адрес {address} был проверен первым: {error}", "endpoints_unverified": "Найдено локальных служб SSH: {count}, но ни одна не подтверждена как этот Kindle с KOReader.", "no_tcp_answer": "Ни одно локальное устройство не ответило на TCP 2222. Убедитесь, что SSH KOReader запущен и Wi-Fi не изолирует клиентов.", "new_computer_help": "На новом компьютере остановите SSH KOReader, включите вход без пароля, снова запустите SSH, отметьте эту опцию в приложении и подключитесь повторно.", "sending_file": "Отправка {name} - {sent} из {size}", "no_readable_files": "Не выбраны читаемые файлы книг.", "connecting_secure": "Защищённое подключение к {address}...", "create_books_failed": "Не удалось создать папку Books.", "transfer_cancelled": "Передача отменена.", "connection_closed": "Соединение с Kindle неожиданно закрыто.", "sent_book_count": "Отправлено книг: {count}.",
    },
}


_EXTRA_TRANSLATIONS = {
    "en": {
        "address_history": "Previously connected Kindle addresses",
        "storage": "Kindle storage",
        "storage_waiting": "Connect a Kindle to view storage usage.",
        "storage_summary": "{used} used of {total} · {free} free · {percent}% used",
        "storage_last_summary": "Last known: {used} used of {total} · {free} free · {percent}% used",
        "storage_unavailable": "Storage usage is unavailable for this connection.",
        "recent_transfers": "Recent transfers",
        "clear_history": "Clear history",
        "no_history": "Completed transfers will appear here.",
        "history_time": "Time",
        "history_books": "Books",
        "history_size": "Size",
        "history_kindle": "Kindle",
    },
    "ar": {
        "address_history": "عناوين Kindle المتصلة سابقًا", "storage": "مساحة Kindle", "storage_waiting": "صِل Kindle لعرض استخدام المساحة.", "storage_summary": "المستخدم {used} من {total} · المتاح {free} · مستخدم {percent}%", "storage_last_summary": "آخر قراءة: المستخدم {used} من {total} · المتاح {free} · مستخدم {percent}%", "storage_unavailable": "استخدام المساحة غير متاح لهذا الاتصال.", "recent_transfers": "عمليات النقل الأخيرة", "clear_history": "مسح السجل", "no_history": "ستظهر عمليات النقل المكتملة هنا.", "history_time": "الوقت", "history_books": "الكتب", "history_size": "الحجم", "history_kindle": "Kindle",
    },
    "es": {
        "address_history": "Direcciones Kindle conectadas anteriormente", "storage": "Almacenamiento del Kindle", "storage_waiting": "Conecta un Kindle para ver el uso del almacenamiento.", "storage_summary": "{used} usados de {total} · {free} libres · {percent}% usado", "storage_last_summary": "Último dato: {used} usados de {total} · {free} libres · {percent}% usado", "storage_unavailable": "El uso del almacenamiento no está disponible para esta conexión.", "recent_transfers": "Transferencias recientes", "clear_history": "Borrar historial", "no_history": "Las transferencias completadas aparecerán aquí.", "history_time": "Hora", "history_books": "Libros", "history_size": "Tamaño", "history_kindle": "Kindle",
    },
    "fr": {
        "address_history": "Adresses Kindle déjà connectées", "storage": "Stockage du Kindle", "storage_waiting": "Connectez un Kindle pour afficher l’utilisation du stockage.", "storage_summary": "{used} utilisés sur {total} · {free} libres · {percent}% utilisés", "storage_last_summary": "Dernière mesure : {used} utilisés sur {total} · {free} libres · {percent}% utilisés", "storage_unavailable": "L’utilisation du stockage n’est pas disponible pour cette connexion.", "recent_transfers": "Transferts récents", "clear_history": "Effacer l’historique", "no_history": "Les transferts terminés apparaîtront ici.", "history_time": "Heure", "history_books": "Livres", "history_size": "Taille", "history_kindle": "Kindle",
    },
    "ja": {
        "address_history": "以前接続したKindleアドレス", "storage": "Kindleストレージ", "storage_waiting": "Kindleを接続するとストレージ使用量を表示します。", "storage_summary": "{total} 中 {used} 使用 · 空き {free} · {percent}% 使用", "storage_last_summary": "前回：{total} 中 {used} 使用 · 空き {free} · {percent}% 使用", "storage_unavailable": "この接続ではストレージ使用量を取得できません。", "recent_transfers": "最近の転送", "clear_history": "履歴を消去", "no_history": "完了した転送がここに表示されます。", "history_time": "日時", "history_books": "冊数", "history_size": "サイズ", "history_kindle": "Kindle",
    },
    "ko": {
        "address_history": "이전에 연결한 Kindle 주소", "storage": "Kindle 저장 공간", "storage_waiting": "저장 공간 사용량을 보려면 Kindle을 연결하세요.", "storage_summary": "{total} 중 {used} 사용 · {free} 남음 · {percent}% 사용", "storage_last_summary": "마지막 기록: {total} 중 {used} 사용 · {free} 남음 · {percent}% 사용", "storage_unavailable": "이 연결에서는 저장 공간 사용량을 확인할 수 없습니다.", "recent_transfers": "최근 전송", "clear_history": "기록 지우기", "no_history": "완료된 전송이 여기에 표시됩니다.", "history_time": "시간", "history_books": "책", "history_size": "크기", "history_kindle": "Kindle",
    },
    "vi": {
        "address_history": "Địa chỉ Kindle đã kết nối", "storage": "Bộ nhớ Kindle", "storage_waiting": "Kết nối Kindle để xem mức sử dụng bộ nhớ.", "storage_summary": "Đã dùng {used} / {total} · còn {free} · đã dùng {percent}%", "storage_last_summary": "Lần gần nhất: đã dùng {used} / {total} · còn {free} · đã dùng {percent}%", "storage_unavailable": "Không thể đọc mức sử dụng bộ nhớ cho kết nối này.", "recent_transfers": "Lần truyền gần đây", "clear_history": "Xóa lịch sử", "no_history": "Các lần truyền hoàn tất sẽ xuất hiện ở đây.", "history_time": "Thời gian", "history_books": "Sách", "history_size": "Kích thước", "history_kindle": "Kindle",
    },
    "zh-Hans": {
        "address_history": "以前连接过的 Kindle 地址", "storage": "Kindle 存储空间", "storage_waiting": "连接 Kindle 后显示存储用量。", "storage_summary": "已用 {used} / {total} · 可用 {free} · 已用 {percent}%", "storage_last_summary": "上次记录：已用 {used} / {total} · 可用 {free} · 已用 {percent}%", "storage_unavailable": "本次连接无法读取存储用量。", "recent_transfers": "最近传输", "clear_history": "清除历史", "no_history": "完成的传输会显示在这里。", "history_time": "时间", "history_books": "图书", "history_size": "大小", "history_kindle": "Kindle",
    },
    "zh-Hant": {
        "address_history": "以前連接過的 Kindle 位址", "storage": "Kindle 儲存空間", "storage_waiting": "連接 Kindle 後顯示儲存用量。", "storage_summary": "已用 {used} / {total} · 可用 {free} · 已用 {percent}%", "storage_last_summary": "上次記錄：已用 {used} / {total} · 可用 {free} · 已用 {percent}%", "storage_unavailable": "本次連線無法讀取儲存用量。", "recent_transfers": "最近傳輸", "clear_history": "清除歷史", "no_history": "完成的傳輸會顯示在這裡。", "history_time": "時間", "history_books": "書籍", "history_size": "大小", "history_kindle": "Kindle",
    },
    "de": {
        "address_history": "Zuvor verbundene Kindle-Adressen", "storage": "Kindle-Speicher", "storage_waiting": "Kindle verbinden, um die Speichernutzung anzuzeigen.", "storage_summary": "{used} von {total} belegt · {free} frei · {percent}% belegt", "storage_last_summary": "Letzter Stand: {used} von {total} belegt · {free} frei · {percent}% belegt", "storage_unavailable": "Die Speichernutzung ist für diese Verbindung nicht verfügbar.", "recent_transfers": "Letzte Übertragungen", "clear_history": "Verlauf löschen", "no_history": "Abgeschlossene Übertragungen erscheinen hier.", "history_time": "Zeit", "history_books": "Bücher", "history_size": "Größe", "history_kindle": "Kindle",
    },
    "ru": {
        "address_history": "Ранее подключённые адреса Kindle", "storage": "Хранилище Kindle", "storage_waiting": "Подключите Kindle, чтобы увидеть использование хранилища.", "storage_summary": "Использовано {used} из {total} · свободно {free} · занято {percent}%", "storage_last_summary": "Последние данные: использовано {used} из {total} · свободно {free} · занято {percent}%", "storage_unavailable": "Для этого подключения данные хранилища недоступны.", "recent_transfers": "Последние передачи", "clear_history": "Очистить историю", "no_history": "Завершённые передачи появятся здесь.", "history_time": "Время", "history_books": "Книги", "history_size": "Размер", "history_kindle": "Kindle",
    },
}

for _language_code, _extra_strings in _EXTRA_TRANSLATIONS.items():
    _TRANSLATIONS.setdefault(_language_code, {}).update(_extra_strings)


_INSTALL_TRANSLATIONS = {
    "en": {"install_title": "Keep the sender close", "install_body": "The packaged app maintains its installed copy and Start menu shortcut automatically.", "add_start": "Add to Start", "add_taskbar": "Add to taskbar", "start_installed": "Kindle Book Sender is installed and available from the Start menu.", "taskbar_installed": "Windows accepted the taskbar pin request.", "taskbar_manual": "Windows did not expose automatic taskbar pinning. Right-click the running taskbar icon and choose Pin to taskbar.", "install_requires_build": "Install controls are available in the packaged app, not when running from Python source.", "install_failed": "The app could not be installed: {error}"},
    "ar": {"install_title": "احتفظ بالتطبيق قريبًا", "install_body": "تحافظ النسخة المجمعة تلقائيًا على النسخة المثبتة واختصار قائمة ابدأ.", "add_start": "إضافة إلى ابدأ", "add_taskbar": "إضافة إلى شريط المهام", "start_installed": "تم تثبيت Kindle Book Sender وأصبح متاحًا من قائمة ابدأ.", "taskbar_installed": "قبل Windows طلب التثبيت في شريط المهام.", "taskbar_manual": "لم يسمح Windows بالتثبيت التلقائي. انقر بزر الفأرة الأيمن على أيقونة التطبيق في شريط المهام واختر التثبيت.", "install_requires_build": "تتوفر خيارات التثبيت في النسخة المجمعة، وليس عند التشغيل من مصدر Python.", "install_failed": "تعذر تثبيت التطبيق: {error}"},
    "es": {"install_title": "Ten el Sender siempre a mano", "install_body": "La aplicación empaquetada mantiene automáticamente su copia instalada y el acceso del menú Inicio.", "add_start": "Añadir a Inicio", "add_taskbar": "Anclar a la barra de tareas", "start_installed": "Kindle Book Sender está instalado y disponible en el menú Inicio.", "taskbar_installed": "Windows aceptó la solicitud de anclaje.", "taskbar_manual": "Windows no permitió el anclaje automático. Haz clic derecho en el icono activo y elige Anclar a la barra de tareas.", "install_requires_build": "Los controles de instalación están disponibles en la aplicación empaquetada, no desde Python.", "install_failed": "No se pudo instalar la aplicación: {error}"},
    "fr": {"install_title": "Gardez le Sender à portée de main", "install_body": "L’application empaquetée maintient automatiquement sa copie installée et son raccourci du menu Démarrer.", "add_start": "Ajouter au menu Démarrer", "add_taskbar": "Épingler à la barre des tâches", "start_installed": "Kindle Book Sender est installé et disponible depuis le menu Démarrer.", "taskbar_installed": "Windows a accepté la demande d’épinglage.", "taskbar_manual": "Windows n’a pas autorisé l’épinglage automatique. Faites un clic droit sur l’icône active et choisissez Épingler à la barre des tâches.", "install_requires_build": "Les commandes d’installation sont disponibles dans l’application empaquetée, pas depuis Python.", "install_failed": "Impossible d’installer l’application : {error}"},
    "ja": {"install_title": "Senderをすぐ使える場所に", "install_body": "パッケージ版はインストール済みコピーとスタートメニューのショートカットを自動で維持します。", "add_start": "スタートに追加", "add_taskbar": "タスクバーに追加", "start_installed": "Kindle Book Senderをインストールし、スタートメニューに追加しました。", "taskbar_installed": "Windowsがタスクバーへのピン留め要求を受け付けました。", "taskbar_manual": "Windowsが自動ピン留めを許可しませんでした。実行中のアイコンを右クリックしてピン留めしてください。", "install_requires_build": "インストール機能はパッケージ版で利用できます。Python実行時には使用できません。", "install_failed": "アプリをインストールできませんでした：{error}"},
    "ko": {"install_title": "Sender를 가까이 두기", "install_body": "패키지 앱은 설치된 복사본과 시작 메뉴 바로 가기를 자동으로 유지합니다.", "add_start": "시작 메뉴에 추가", "add_taskbar": "작업 표시줄에 추가", "start_installed": "Kindle Book Sender가 설치되어 시작 메뉴에서 사용할 수 있습니다.", "taskbar_installed": "Windows가 작업 표시줄 고정 요청을 수락했습니다.", "taskbar_manual": "Windows가 자동 고정을 허용하지 않았습니다. 실행 중인 아이콘을 오른쪽 클릭하여 고정하세요.", "install_requires_build": "설치 기능은 패키지 앱에서만 사용할 수 있습니다.", "install_failed": "앱을 설치할 수 없습니다: {error}"},
    "vi": {"install_title": "Giữ Sender luôn tiện dùng", "install_body": "Bản đóng gói tự duy trì bản đã cài và lối tắt menu Start.", "add_start": "Thêm vào Start", "add_taskbar": "Thêm vào thanh tác vụ", "start_installed": "Kindle Book Sender đã được cài và có trong menu Start.", "taskbar_installed": "Windows đã chấp nhận yêu cầu ghim.", "taskbar_manual": "Windows không cho phép tự động ghim. Hãy bấm phải biểu tượng đang chạy và chọn ghim.", "install_requires_build": "Tính năng cài đặt chỉ có trong ứng dụng đã đóng gói.", "install_failed": "Không thể cài ứng dụng: {error}"},
    "zh-Hans": {"install_title": "让传书工具随手可用", "install_body": "打包版会自动维护已安装副本和开始菜单快捷方式。", "add_start": "添加到开始菜单", "add_taskbar": "添加到任务栏", "start_installed": "Kindle Book Sender 已安装，可从开始菜单打开。", "taskbar_installed": "Windows 已接受任务栏固定请求。", "taskbar_manual": "Windows 未开放自动固定。请右键单击正在运行的任务栏图标，然后选择“固定到任务栏”。", "install_requires_build": "安装功能仅在打包版中可用，从 Python 源码运行时不可用。", "install_failed": "无法安装应用：{error}"},
    "zh-Hant": {"install_title": "讓傳書工具隨手可用", "install_body": "封裝版會自動維護已安裝副本和開始功能表捷徑。", "add_start": "加入開始功能表", "add_taskbar": "加入工作列", "start_installed": "Kindle Book Sender 已安裝，可從開始功能表開啟。", "taskbar_installed": "Windows 已接受工作列釘選要求。", "taskbar_manual": "Windows 未開放自動釘選。請在執行中的圖示按右鍵，然後選擇釘選。", "install_requires_build": "安裝功能僅在封裝版中可用。", "install_failed": "無法安裝應用程式：{error}"},
    "de": {"install_title": "Sender griffbereit halten", "install_body": "Die gepackte App pflegt ihre installierte Kopie und Startmenü-Verknüpfung automatisch.", "add_start": "Zum Startmenü hinzufügen", "add_taskbar": "An Taskleiste anheften", "start_installed": "Kindle Book Sender ist installiert und im Startmenü verfügbar.", "taskbar_installed": "Windows hat die Anforderung zum Anheften angenommen.", "taskbar_manual": "Windows hat automatisches Anheften nicht angeboten. Rechtsklicke das laufende Symbol und hefte es an.", "install_requires_build": "Installationsfunktionen sind nur in der gepackten App verfügbar.", "install_failed": "Die App konnte nicht installiert werden: {error}"},
    "ru": {"install_title": "Держите Sender под рукой", "install_body": "Упакованная версия автоматически поддерживает установленную копию и ярлык меню «Пуск».", "add_start": "Добавить в меню «Пуск»", "add_taskbar": "Закрепить на панели задач", "start_installed": "Kindle Book Sender установлен и доступен в меню «Пуск».", "taskbar_installed": "Windows приняла запрос на закрепление.", "taskbar_manual": "Windows не разрешила автоматическое закрепление. Щёлкните правой кнопкой значок приложения и закрепите его.", "install_requires_build": "Установка доступна только в упакованной версии.", "install_failed": "Не удалось установить приложение: {error}"},
}

for _language_code, _install_strings in _INSTALL_TRANSLATIONS.items():
    _TRANSLATIONS.setdefault(_language_code, {}).update(_install_strings)


# Security-sensitive shared-key disclosures intentionally remain identical in
# every locale until reviewed translations are available. A stale translation
# must never describe this published, bundled identity as a per-computer secret.
_SHARED_KEY_DISCLOSURES = {
    "preparing_key": "Verifying the shared Kindle-only key...",
    "no_password_tooltip": "The app will use no-password access once, install the shared published Kindle-only public key, and verify key login. It will not disable the Kindle setting.",
    "footer": "Version {version}  ·  Shared published Kindle-only key  ·  Stop KOReader SSH when finished",
    "paired_auto": "Paired automatically on {roots} with the shared Kindle-only identity.",
    "first_use_usb": "If this Kindle has not authorized the shared key, connect it by USB once or use no-password Wi-Fi pairing.",
    "bootstrap_success": "Passwordless bootstrap succeeded. The shared Kindle-only public key was installed and key login was verified.",
    "key_verified": "Verified with the pinned shared Kindle-only key and the KOReader installation.",
    "new_computer_help": "If the shared key is not authorized, stop KOReader SSH, enable 'Login without password (DANGEROUS)', start SSH, check the app's no-password option, and connect again.",
}
for _language_code in _TRANSLATIONS:
    _TRANSLATIONS[_language_code].update(_SHARED_KEY_DISCLOSURES)


_current_language = "en"


_FREE_BOOK_LABELS = {
    "en": "Free LinguaLeaf books",
    "ar": "كتب LinguaLeaf مجانية",
    "es": "Libros LinguaLeaf gratis",
    "fr": "Livres LinguaLeaf gratuits",
    "ja": "LinguaLeaf 無料書籍",
    "ko": "무료 LinguaLeaf 책",
    "vi": "Sách LinguaLeaf miễn phí",
    "zh-Hans": "免费 LinguaLeaf 读物",
    "zh-Hant": "免費 LinguaLeaf 讀物",
    "de": "Kostenlose LinguaLeaf-Bücher",
    "ru": "Бесплатные книги LinguaLeaf",
}
for _language, _label in _FREE_BOOK_LABELS.items():
    _TRANSLATIONS.setdefault(_language, {})["free_books"] = _label


def normalize_language(value: str | None) -> str:
    code = (value or "").replace("_", "-").strip().lower()
    if code.startswith("zh"):
        if any(marker in code for marker in ("hant", "tw", "hk", "mo")):
            return "zh-Hant"
        return "zh-Hans"
    for supported, _ in LANGUAGES:
        if code == supported.lower() or code.startswith(supported.lower() + "-"):
            return supported
    return "en"


def set_language(value: str | None) -> str:
    global _current_language
    _current_language = normalize_language(value)
    return _current_language


def current_language() -> str:
    return _current_language


def tr(key: str, **values: object) -> str:
    translated = _TRANSLATIONS.get(_current_language, {}).get(key)
    template = translated if translated is not None else _ENGLISH.get(key, key)
    try:
        return template.format(**values)
    except (KeyError, ValueError):
        return template
